var JobData = {
  2001: [{ id: 1,
          title:"Software Engineer Grade 4",
          task:"7xxx platform feature and bug fixing",
          role:"Individual Contributer",
          teamsize: 1,
          tech:"C",
          company:"Cisco Systems",
          desc:["Fixed bugs on 7200 and 7500 router platforms","Ported subrate functionality to a new release of IOS with only 3 new bugs found."]
  }],
  2003: [{ id: 2,
           title:"Software Engineer Grade 6",
           role:"Component Manager",
           task:"T3/E3 port adaptor ownership",
           teamsize:2,
           tech:"C",
           company:"Cisco Systems",
           desc:["Ownership of features and bugs on T3/E3 port adaptors", "drove down bug count to single digits on all components using phase control methods"]},{ id: 3,
    title: "Software Engineer Grade 6",
    role:"Individual Contributer",
    task:"Design and development of features for 7xxx platforms",
    teamsize:1,
    tech:"C",
    company:"Cisco Systems",
    desc:["Design and developed the driver for Enhanced T3E3 Port Adaptor","* Proved improved performance in design","* Received a patent for this work http://www.freshpatents.com/dt20090108ptan20090010157.php","Designed and developed Dial-on-Demand Routing for 7500 platform", "Designed and developed Minimum Disruptive Reload for Channelized T3/E3 port adaptors"]}],
  2005: [{ id: 4,
           title: "Senior Software Engineer Grade 8",
           role: "Lead Engineer",
           task:"Implement protocol matching using STILE",
           teamsize: 6,
           company:"Cisco Systems",
           tech:"STILE",
           desc:["STILE is a language developed by Cisco to match protocols in a network.","It is an integral part of Network Based Application Recognition NBAR.","I had to learn this language and train the rest of my team and start writing the matching code for newer protocols like webex"]},
         { id: 5,
           title: "Senior Software Engineer Grade 8",
           role: "Lead Engineer",
           company:"Cisco Systems",
           task: "Transfer 10720 platform ownership to India",
           teamsize: 6,
           tech:"C,Assembly",
           desc:["Learnt about the 10720 platform from Canada team.","The 10720 switching Asic (Toaster) is programmed in 2 pipeline assembly.","Once back in India I trained the team to own the development and bug fixing","Created a Wiki to aid the knowledge transfer to the rest of the team","Recognized by the director for being the single point of contact for this platform in one month"]},
         { id: 6,
           title: "Senior Software Engineer Grade 8",
           role: "Lead Engineer",
           company:"Cisco Systems",
           task: "Transfer 7300 platform ownership to India",
           teamsize: 6,
           tech:"C, Assembly",
           desc:["Learnt about 7300 platform from Australia team.","The 7300 switching Asic (Toaser) is programmed in 2 pipeline assembly.","Apart from training the team to handle bugs independently I was personally responsible for QOS"]},
         { id: 7,
           title: "Senior Software Engineer Grade 8",
           role: "Lead Engineer",
           company:"Cisco Systems",
           task: "SPA team mentoring and bug backlog reduction",
           teamsize: 6,
           tech: "C",
           desc:["Mentor and train the SPA team to become more productive.",
           "Took and arranged trainings for the whole team on technology and debugging.","Increased productivity from 7 bugs fixed in 3 months to 50 in a single month"]},
         { id: 8,
           title: "Senior Software Engineer Grade 8",
           role: "Individual Contributer",
           company:"Cisco Systems",
           task: "LFI development on OC12 card",
           tech: "C++",
           desc:["The ucode for this card was compiled from C++.","Implemented LFI feature on this card"]}],
   2009: [{ id: 9,
            title: "Senior Software Engineer Grade 10",
            role: "Architect",
            company:"Cisco Systems",
            task: "Design the architecture for next generation mobile routers",
            tech: "Design",
            desc:["As part of Emerging Technical Leaders Program, worked with marketing engineers to layout the requirements for the next generation mobile router architecture.","Designed an architecture to implement these requirements on existing IOS platforms"]},
          { id: 10,
            title: "Senior Software Engineer Grade 10",
            role: "Individual Contributer",
            company:"Cisco Systems",
            task: "Design and develop WAAS on asr1k platform",
            tech: "C",
            desc:["Wide Area Application Services (WAAS) are features that can optimize traffic used by Applications on a network.","I was specifically looking at compression of traffic streams over the WAN links","Created a prototype"]},
          { id: 11,
            title: "Senior Software Engineer Grade 10",
            role: "Individual Contributer",
            company:"Cisco Systems",
            task: "Design and develop SRP on ASR1K",
            desc:["Spatial Reuse Protocol is a ring protocol which gives resilience to ring networks.","I implemented this on ASR1K platform"]},
          { id: 12,
            title: "Senior Software Engineer Grade 10",
            company:"Cisco Systems",
            role: "Side business",
            task: "Improve productivity of the team",
            desc:["Wrote a script to reduce the time required to copy images to US servers by opening many parallel connections","Wrote a curses tool to view and edit bugs from ddts (the bug tracking tool)","Wrote a wrapper for gid to remember the history of gid searches"]}]

