var JobData = {
  2001: [{ id: 1,
          title:"Software Engineer Grade 4",
          task:"7xxx platform feature and bug fixing",
          role:"Individual Contributer",
          teamsize: 1,
          tech:"C",
          company:"Cisco Systems",
          desc:["Fixed bugs on 7200 and 7500 router platforms","Ported subrate functionality to a new release of IOS with only 3 new bugs found."]
  }],
  2003: [{ id: 2,
           title:"Software Engineer Grade 6",
           role:"Component Manager",
           task:"T3/E3 port adaptor ownership",
           teamsize:2,
           tech:"C",
           company:"Cisco Systems",
           desc:["Ownership of features and bugs on T3/E3 port adaptors", "drove down bug count to single digits on all components using phase control methods"]},{ id: 3,
    title: "Software Engineer Grade 6",
    role:"Individual Contributer",
    task:"Design and development of features for 7xxx platforms",
    teamsize:1,
    tech:"C",
    company:"Cisco Systems",
    desc:["Design and developed the driver for Enhanced T3E3 Port Adaptor","* Proved improved performance in design","* Received a patent for this work http://www.freshpatents.com/dt20090108ptan20090010157.php","Designed and developed Dial-on-Demand Routing for 7500 platform", "Designed and developed Minimum Disruptive Reload for Channelized T3/E3 port adaptors"]}],
  2005: [{ id: 4,
           title: "Senior Software Engineer Grade 8",
           role: "Lead Engineer",
           task:"Implement protocol matching using STILE",
           teamsize: 6,
           company:"Cisco Systems",
           tech:"STILE",
           desc:["STILE is a language developed by Cisco to match protocols in a network.","It is an integral part of Network Based Application Recognition NBAR.","I had to learn this language and train the rest of my team and start writing the matching code for newer protocols like webex"]},
         { id: 5,
           title: "Senior Software Engineer Grade 8",
           role: "Lead Engineer",
           company:"Cisco Systems",
           task: "Transfer 10720 platform ownership to India",
           teamsize: 6,
           tech:"C,Assembly",
           desc:["Learnt about the 10720 platform from Canada team.","The 10720 switching Asic (Toaster) is programmed in 2 pipeline assembly.","Once back in India I trained the team to own the development and bug fixing","Created a Wiki to aid the knowledge transfer to the rest of the team","Recognized by the director for being the single point of contact for this platform in one month"]},
         { id: 6,
           title: "Senior Software Engineer Grade 8",
           role: "Lead Engineer",
           company:"Cisco Systems",
           task: "Transfer 7300 platform ownership to India",
           teamsize: 6,
           tech:"C, Assembly",
           desc:["Learnt about 7300 platform from Australia team.","The 7300 switching Asic (Toaser) is programmed in 2 pipeline assembly.","Apart from training the team to handle bugs independently I was personally responsible for QOS"]},
         { id: 7,
           title: "Senior Software Engineer Grade 8",
           role: "Lead Engineer",
           company:"Cisco Systems",
           task: "SPA team mentoring and bug backlog reduction",
           teamsize: 6,
           tech: "C",
           desc:["Mentor and train the SPA team to become more productive.",
           "Took and arranged trainings for the whole team on technology and debugging.","Increased productivity from 7 bugs fixed in 3 months to 50 in a single month"]},
         { id: 8,
           title: "Senior Software Engineer Grade 8",
           role: "Individual Contributer",
           company:"Cisco Systems",
           teamsize: 1,
           task: "LFI development on OC12 card",
           tech: "C++",
           desc:["The ucode for this card was compiled from C++.","Implemented LFI feature on this card"]}],
   2009: [{ id: 9,
            title: "Senior Software Engineer Grade 10",
            role: "Architect",
            teamsize: 4,
            company:"Cisco Systems",
            task: "Design the architecture for next generation mobile routers",
            tech: "Design",
            desc:["As part of Emerging Technical Leaders Program, worked with marketing engineers to layout the requirements for the next generation mobile router architecture.","Designed an architecture to implement these requirements on existing IOS platforms"]},
          { id: 10,
            title: "Senior Software Engineer Grade 10",
            role: "Individual Contributer",
            teamsize: 1,
            company:"Cisco Systems",
            task: "Design and develop WAAS on asr1k platform",
            tech: "C",
            desc:["Wide Area Application Services (WAAS) are features that can optimize traffic used by Applications on a network.","I was specifically looking at compression of traffic streams over the WAN links","Created a prototype"]},
          { id: 11,
            title: "Senior Software Engineer Grade 10",
            role: "Individual Contributer",
            teamsize: 1,
            company:"Cisco Systems",
            tech: "C",
            task: "Design and develop SRP on ASR1K",
            desc:["Spatial Reuse Protocol is a ring protocol which gives resilience to ring networks.","I implemented this on ASR1K platform"]},
          { id: 12,
            title: "Senior Software Engineer Grade 10",
            company:"Cisco Systems",
            teamsize: 1,
            tech: "C",
            role: "Side business",
            task: "Improve productivity of the team",
            desc:["Wrote a script to reduce the time required to copy images to US servers by opening many parallel connections","Wrote a curses tool to view and edit bugs from ddts (the bug tracking tool)","Wrote a wrapper for gid to remember the history of gid searches"]}]
   2010: [{ id: 13,
            title: "Senior Software Engineer",
            company:"Zynga",
            role: "Individual Contributer",
            tech: "php",
            teamsize: 1,
            task: "Server optimization"
            desc:["Profiled Zynga games and suggested improvements that reduced the server count by 50%","Changes included setting cache header on certain assets, Code profiling and Rewriting or eliminating certain code loops, Increasing the number of processes spawned by Apache"]},
          { id: 14,
            title: "Senior Software Engineer",
            company: "Zynga",
            role: "Individual Contributer",
            tech: "php,C++",
            teamsize: "1",
            task: "Make HipHop work on Zynga codebase",
            desc: ["Hiphop is a php to C++ converter developed by facebook","It didnt run well on Zynga codebase due to certain php practices.","I successfully fixed the code or fixed Hiphop to get Zynga games on hiphop.","This involved undoing some of the optimizations in hiphop and going though the php code to removecertain usages."]}],
   2011: [{ id: 14,
            title: "Principal Software Engineer",
            company: "Zynga",
            role: "Architect",
            teamsize: 2,
            tech: "php,C++",
            task: "Integrate Hiphop into more games",
            desc: ["Implemented an architecture to deploy games on Hiphop.","Designed a set of scripts to move games to Hiphop in hours. Farmville moved to Hiphop during a Hackathon. Integration time moved from days to hours.", "Integrated Cityville with Hiphop.","Integrated Continuous development with Hiphop"]},
          { id: 15,
            title: "Principal Software Engineer",
            company: "Zynga",
            role: "Individual Contributer",
            teamsize: 2,
            tech: "php,python,Vertica",
            task: "Measure and improve User Experience",
            desc: ["Came up with an emperical formula to measure technological effects on User experience. It is based on the delay experienced by a user.","Built the framework and the dashboard to show this data. We used Vertica to store the data from the users and analyze it.","Also built a prototype for a flash profiler"]},
          { id: 16,
            title: "Principal Software Engineer",
            company: "Zynga",
            role: "Lead Engineer",
            teamsize: 5,
            tech: "javascript,php",
            task: "Transition Zynga.com to India",
            desc: ["Zynga.com was written in Zynga's own javascript framework. I was tasked with learning that and training engineers in India on it. Finally, I was tasked with adding new features with appropriate stats and testing built in."]}],
   2013: [{ id: 17,
            title: "Technical Leader",
            company: "Cisco Systems",
            role: "Lead Engineer",
            teamsize: 3,
            tech: "C",
            task: "Adjacency Manager Hardening",
            desc: ["Adjacency manager was a small team inundated with bugs. All switching and routing code had to call this component during configuration. There were many errors in how the switching and routing code used the apis for this component which led to crashes which landed up in adjacency manager bugs. These bugs would ultimately be triaged to the appropriate routing code, but this was eating up the time of the team. I designed and implemented code which checks for proper usage at the boundary of the component. If an anomaly is seen the box would crash pointing fingers at the offending routing code. Bug counts on our component dropped and overall quality shot up, as the tooling spotted even vague memory reuse issues quickly.", "Implemented a memory management UI to track the amount of memory we are allocating. This helped in catching memory leaks early on","Implemented a context sensitive logging, which would tell you the value of all related datastructures in the log text of an error. This speeds up debugging as you dont need to add a new log just to know the value of a datastructure during debugging."]},
           { id: 18,
             title: "Technical Leader",
             company: "Cisco Systems",
             role: "Side Business",
             teamsize: 1,
             tech: "Linux Kernel, Shell",
             task: "Improve Build Time",
             desc: ["A fresh build may take from 2 hrs to a whole day. I wrote some scripts to collect data on builds and tracked down the reason for this variance. We were able to fix this, to give everyone a uniform 2 hr build time.","I then developed a build system using btrfs (A Copy on Write filesystem) which reduced the 2hrs to 25 minutes. Used this in our team as well and finally handed it over IT to develop on it"]}]
   2014: [{ id: 19,
            title: "Technical Leader",
            company: "Cisco Systems",
            role: "Scrum master",
            teamsize: 22,
            task: "Bringup, Infra Development for RSP3 platform",
            tech: "C",
            desc: ["Transitioned the team to scrum. Ran the daily standup and helped unblock engineers by providing necessary information and resources. Accelerated development by providing infra to allow team members to POC their code early. We were able to hit our deadline well in time and ship the platform in record time. Infact we were able to ping using real code talking to an eval board even before hardware was ready"]},
          { id: 20,
            title: "Technical Leader",
            company: "Cisco Systems",
            role: "Individual Contributer",
            task: "Infrastructure for RSP3 platform",
            tech: "C",
            desc: ["RSP3 platform has a very complicated Interface Module infrastructure. Interface Modules need to be placed only in appropriate slots and certain combinations do not work. I created an infrastructure to make this expandable and dependable. We also provided information to the user as to where he can place an IM if he places the IM in a wrong slot.","Created an Infra to allow engineers to quickly prototype their code by bypassing the layers and layers that they would normally have to code up. This enabled many engineers to design their features faster. Also led to early development of debugging code which normally would be relegated to the end.","Dynamic interface was a new feature from the chip vendor and came is bursts. I was able to keep the feature teams running by adding infra to unblock them. I made sure feature teams had their basic requirements.", "Provided infra to track API calls to the Vendor's SDK so that engineers could quickly see what API calls happened"]}],
   2015: [{ id: 21,
            title: "Technical Leader",
            company: "Cisco Systems",
            role: "Mentor/Team Lead",
            task: "IM compatability tool",
            tech: "AngularJS,C", 
            teamsize: 2,
            desc: ["In RSP3 the workable combination of Interface Modules (IM) is quite complex. I came up with an innovative way to make this easier through a dynamic web application.","I was given 2 New College Hires to bring the tool to production.","The tool supports the following features:","The UI is a picture of the actual Router and actual IM front panels. When you place an IM it is shown in the slot that you place it in.", "Informs the User which slots are allowed for an IM. Users can click on these highlighted slots to place the IMs","Takes into account the Release of software that is running on the router as the compatability matrix may change with release","Takes into account certain features like IPSEC that change the compatability matrix","Allows you to save a particular configuration for later viewing and sharing","Given a list of IMs, it provides the allowed combinations of those IMs and shows them to the user","Extended to support RSP3-200, TDM versions of RSP3 and a number of new IMs","It is presently the source of truth of the IM compatability matrix."]},
            { id: 22,
              title: "Technical Leader",
              company: "Cisco Systems",
              role: "Mentor/Team Lead",
              task: "TBOT intelligent debugger",
              technology: "django,python",
              teamsize: 5,
              desc: ["A constant source of pain in debugging issues from the field is the collecting of appropriate data from the router before reloading it. In most cases issues do not appear in the same router after reload. If the Customer Service Engineer (CSE) doesnt get hold of a senior engineer, the junior engineer may ask for data that is insufficient to debug the issue or worse ask for a command that may crash the box. Effects of a crash are obvious, but the lack of enough information leads to a back and forth between CSE and Engineering. This is extremely costly for Cisco.","TBOT solves this issue in the following way:","1. One web portal to collect all data from the router. This allows easy analysis of data as opposed to pouring over unending email chains.","2. Intelligent generation of scripts to collect data from the router. The CSE just needs to know the superficials of the issue and TBOT will provide a script to collect all relevant data. These scripts are easy to write and maintain.","3. Console for viewing the logs collected, allowing for easy organization of the data. Tab completed command search, feels like you are actually sitting at a router","4. Automated first level triage. Provides a simple infrastructure to write tests on the data. These tests are designed to use as much data as available and flag missing data for further development. They can automatically surface consistency issues in the show commands. This gives engineers a quick way to get to the heart of the problem."]}]  
   2016: [{ id: 22,
            title: "Technical Leader",
            company: "Cisco Systems",
            role: "Mentor/Team Lead",
            teamsize: 1
            task: "New Hire Rampup tool",
            technology: "django,python",
            desc: ["New Hires are the most ignored engineers in Cisco. They are expected to Rampup all on their own. The first 2 months are generally known as 'the honeymoon period' where new recruits are just left to themselves. They are supposed to rampup on technology but seldom do. After 2 months when their manager starts giving work to the new-hire he wastes another month getting started. The issue is that Mentors or Technical Leads dont have the time to give proper guidance as they themselves would have come up the hard way. This leads to a lot of waste of time and also frustration for the new-hire, sometimes leading to new-hires leaving the company very soon.", "The tool Rampup tries to solve this problem in the following way.","1. The mentors can update a list of things the New-Hire should rampup on in the tool. This includes important links to information and tools the New-hire is supposed to know.","2. Each step in the list can be given a deadline which is just the number of days/hours it should take.","3. The tool tracks the new hire from the time he joins on each of the tasks. Tasks can be ordered or unordered and the tool tracks whether the task is completed on time.","4. Some tasks need to be verified by the manager or mentor and a mail is sent when the task is complete in that case. The manager/mentor then has to approve the tasks for the new-hire to get scored for the task. Manager can also reopen a task if the quality is wanting. This affects the score of the new hire. This enforces quality on the rampup process.","5. The scoring puts the onus of rampup on the new-hire so he reaches out and demands time from managers and mentors.","6. The tool provides monitoring of the progress of the each new-hire through graphs and tables. Alerts can also be created for non-performing new-hires."]}, 
            { id: 23,
              title: "Technical Leader",
              company: "Cisco Systems",
              role: "Team Lead",
              teamsize: 5,
              task: "CodeJam: New College hire Onboarding and assessment Tool",
              technology: "django, python",
              desc: ["Every year about 100 new college hires join our Business Unit in Cisco. These engineers come from a number of colleges and there was felt a need for a program to bring them fast to a level from where they could quickly contribute to the organization. This includes training on C and Python, Platform specific training about the teams they are alloted to, a 3 month project to teach them the Cisco development methodology and create something of value to the company in the shortest possible time and finally tests to measure the baseline knowledge of C and python and how they are progressing.","This year we developed a web tool to do all of these and collect data from each of these aspects. This allows us collect data during the program and course correct next year's program based on this information.","The tool provides the following features:","1. A platform to generate and hold tests on C and python. It allows creation of new questions, programmatic creation of input and solution files, large and small set inputs and even manually created question and answer sets","2. Tests can be scheduled and will appear to all users at specific times.","3. Scores are known instantaneously as the test progresses and the time of solution is also tracked","4. Test takers upload their code as well which can be used for further analysis.","5. Project milestones can be updated and the dashboard will show the progress of each project. It marks projects as Red if they are falling behind their milestones","6. It allows the creation of a scorecard which can be used by the judges during the mid-project readouts of each project. This is important to course correct during the program. This year it told us that we need to focus more on development methodology. The scores by each judge during a readout are available for viewing by the teams and a scoreboard is provided for overall score.","7. Finally a voting app is provided for the audience choice award during the final presentation.","8. One of the key insights we got from the tool this year is while the new College Hires think they are really good at Python and C they fail to write a complete program from scratch".]},
            { id: 24,
              title: "Technical Leader",
              company: "Cisco Systems",
              role: "Individual Contributor",
              task: "Analysis of bug data to gain insights into code quality",
              technology: "Python, Elastic Search, Kibana",
              desc: ["Wrote a webservice that would parse the diffs for a particular bug id and provide the number of changed lines per file and even per function.","Using this data over all the bugs fixed in a component we can easily come up with the hot spots in the code for targetted cleanup.","We can also derive interesting data points like which engineer has churned the most code and also more interestingly fixed the most bugs in the same patches of code. While the former may be a measure of productivity, the second is a measure of how many bugs an engineer creates","Using kibana I was able to create a dashboard for each component drilling upto manager impact on the codebase.","We plan to hook this into the cisco wide bug data analysis tool"]}],
}; 

