bundle.js:  main.js dispatcher.js loading.js timeline.js waiting.js jobdetails.js jobscreen.js carousel.js
	browserify -t [ babelify ] dispatcher.js loading.js timeline.js  waiting.js jobdetails.js carousel.js jobscreen.js main.js -o bundle.js
